NFQWS_OPT_DESYNC="-4 --dpi-desync=fake,disorder2 --dpi-desync-split-pos=2 --dpi-desync-ttl=8 --dpi-desync-fooling=md5sig,badsum"
NFQWS_OPT_DESYNC_RICH=""
NFQQUEUE_NUM=200
IFACE_WAN=""
MODE_HTTP=0
MODE_HTTP_KEEPALIVE=0
MODE_HTTPS=1
MODE_QUIC=0
